### ISSUE TITLE
connectionTimeout

### ISSUE THREAD

**Issue by agausachs** [jinyuttt/Hikari#4]
Hi,

_(HikariConfig.cs)_ Shouldn't connectionTimeout be configured to 30.000 by default instead of 3.000 as on HikariCP?

> **_HikariCP documentation excerpt_**
> ⏳connectionTimeout
> This property controls the maximum number of milliseconds that a client (that's you) will wait for a connection from the pool. If this time is exceeded without a connection becoming available, a SQLException will be thrown. Lowest acceptable connection timeout is 250 ms. Default: 30000 (30 seconds)

**Comment by jinyuttt** [comment]
ok
